---
- name: Backup file ifcfg-{{ interface }}
  copy:
    remote_src: yes
    src: /etc/sysconfig/network-scripts/ifcfg-{{ interface }}
    dest: /etc/sysconfig/network-scripts/bck.ifcfg-{{ interface }}
    mode: 0644

- name: Delete file ifcfg-{{ interface }}
  file:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ interface }}
    state: absent

- name: Create and edit file ifcfg-{{ interface }}
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ interface }}
    state: present
    create: yes
    marker: ""
    block: |
      DEVICE={{ interface }}
      TYPE=OVSPort
      DEVICETYPE=ovs
      OVS_BRIDGE={{ bridge_ext }}
      ONBOOT=yes

- name: Create and edit file ifcfg-{{ bridge_ext }}
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ bridge_ext }}
    state: present
    create: yes
    marker: ""
    block: |
      TYPE=OVSBridge
      BOOTPROTO=static
      DEVICE={{ bridge_ext }}
      DEVICETYPE=ovs
      ONBOOT=yes
      IPADDR={{ br_ex_address }}
      NETMASK={{ br_ex_netmask }}
      GATEWAY={{ br_ex_gateway }}

- name: Create and edit file ifcfg-{{ bridge_int }}
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ bridge_int }}
    state: present
    create: yes
    marker: ""
    block: |
      TYPE=OVSBridge
      BOOTPROTO=static
      DEVICE={{ bridge_int }}
      DEVICETYPE=ovs
      ONBOOT=yes
      IPADDR={{ br_in_address }}
      NETMASK={{ br_in_netmask }}

- name: Restart network
  service:
    name: network
    state: restarted

